### ISSUE TITLE
KeyPad and Profiles not working

### ISSUE THREAD

**Issue by hellzakk** [polihedron/DIY-Reflow-Oven#11]
Hi, i open the Reflow.mod.HMI project file with Nextion Editor v. 1.65.1 and I can start debugging and navigate between pages but the keypad does not work and clicking on the welding profiles does not make them visible on the first page.
I get the same result even loading the project on the display (including the non-mod / original).
Any suggestions? Thank you.

EDIT:
Button 1 Touch Release Event code is print "p1b01" but it's now deprecated [https://nextion.tech/instruction-set/](url)
Maybe the new display with updated firmware are no longer compatible with the "old" code?

**Comment by polihedron** [comment]
Hi there, 
- try to downgrade your nextion editor, 

- use prints with "0" - all parameter, or number of chars:
`prints "p1b01",5`

![Zrzut ekranu 2023-09-28 081343](https://github.com/polihedron/DIY-Reflow-Oven/assets/46649005/f039b04e-d537-4a8c-a626-da01f2365269)

- ask Nextion support.

**Comment by hellzakk** [comment]
Hi polihedron,

i used the Nextion Editor v. 1.60.1 (with Reflow.mod.v1.3.HMI) but got the same problems (also by changing the function of the button)
Here you can see the video of the problem: ![NextionEditor_1_60_1](https://github.com/polihedron/DIY-Reflow-Oven/assets/12200889/2e43bb7b-c3be-4dd0-90ba-d50fa35995b3)

**Comment by polihedron** [comment]
It's not an issue now.
Mcu is receiving commands and sending back strings to keypad, if you want to see input values you will have to put command in the "Instruction Input Area":
`t0.txt="1234"`

![Zrzut ekranu 2023-09-28 124011](https://github.com/polihedron/DIY-Reflow-Oven/assets/46649005/4f600cdd-1550-43d4-bd12-030ec372434e)

or connect STM32F1 dev board and check User MCU Input instead of Keyboard Input.
