### ISSUE TITLE
Does anyone else make this working on bluepill??

### ISSUE THREAD

**Issue by botio** [polihedron/DIY-Reflow-Oven#5]
okay, so I have bought the whole brand new components and did the 1.2 hmi and stm again and again. But the wired thing it's still not working (no number or profile line shows on the nextion screen) ... so I'm wondering it may not working with bluepill ... is there anyone make this working with bluepill?? thanks. BTW, the whole set is working with 1.1 original...

**Comment by polihedron** [comment]
I think you should try harder. Try to debug, put some efort, check why your bluepill is not sending data to nextion display instead of opening and closing issues.
 I got no problems with brand new stm32 blue pill dev board. 
I was not using STM32CubeIDE, just st-link utility, and flash fw with last release bin file.


![IMG_20211125_194525](https://user-images.githubusercontent.com/46649005/143490619-e52d4036-b1b5-44ad-a0a2-469e284afa99.jpg)

**Comment by botio** [comment]
![64FAEADB-8D22-489C-8B48-D2AA31E1D8DC](https://user-images.githubusercontent.com/4170675/143516996-57a754ab-e941-43ba-8c52-569690485cb5.jpeg)
I tried really hard, and the reason I post this issue is to see if anyone else got the same problem like me… I’m wondering my bluepill is fake and the flash size is not real, so I order a blackpill on the way now. If opening issue bothers u, I won’t do this again just didn’t know where else I can ask. Thank u

**Comment by botio** [comment]
Btw… why ur blue pill connect to the PC in the photo? Thanks

**Comment by polihedron** [comment]
I'm using cheap clone stm32bluepill. If your STM32 Blackpill dev board is using STM32F4 family mcu, then it's does not work, because project is designed for STM32F103.
I ordered mine stm32bluepill china clone from here:
https://www.aliexpress.com/item/32653883227.html

Do you have USB to UART converter, and do you know how to use it? 
You still didn't provide additional info about your issue, only sharing your weird experience about mixing binary files.
Magic crystal ball is quite expensive these days, and it's hard to get one in good condition, most of them are somehow broken....

Like I wrote before, can you check that bluepill is working?

After power on bluepill is sending reflow profile chart data, and then constantly temperature readings together with state "IDLE", baudrate is 38400. 
Remember that stm32bluepill is using 3.3V logic, so level shifter is needed, or set usb coverter jumper to proper voltage.

To find out that Nextion display can recieve data via UART you need to:

- connect display to UART converter, 
- run Nextion Editor, then open v1.2 hmi file, 
- from menu choose: Debug, 
- switch Send command from "Simulator", to "Nextion device", 
- choose and connect on your COM port, 
-  at the Instruction Input Area as an string send: 
page 3

if you done this right, and communication is working, then you should see on nextion display reflow parameters menu. 
to come back to main screen with chart send:
page 0

![Screenshot_1](https://user-images.githubusercontent.com/46649005/143554691-653ee156-734c-4ec3-b876-d0f1447d50f2.png)


BTW nice print outs, what material did you choose?

**Comment by botio** [comment]
thanks, I was watching STM32 IDE tutorial right now, since this is kinda my first STM32 project, I'm still learning. But yeah, thank you for the detail info for how to debug, and I'm going to try. 

"USB to UART converter" is the st-link ?? I do have one that's how to connect to CubeIDE.

I did print out the panel with PLA .... bc I will only do reflow under 183C, is it okay? or should I print with ABS?
<img width="841" alt="Screen Shot 2021-11-26 at 6 10 46 PM" src="https://user-images.githubusercontent.com/4170675/143564283-5ed1d790-1cb7-473f-9006-b88be0889286.png">
is ur ST-Link page like this as well? I meant the first line code, thank u

**Comment by polihedron** [comment]
Nope, st-link isn't usb to uart converter (unless it's v2.1 or v3), you should buy one, instead of buying blue pills. Try to find one with ftdi chip (ft232), but any other should work with installed drivers.
Regarding to PLA, depends on how long time will be hot oven enclosure, and how close printed parts will be. 
I printed mine in ASA, but after some time decided to print in PA12 CF15, because I'm using oven quite often.

**Comment by botio** [comment]
Uart converter, I think I found one with ft232. and after connect with bluepill to arduino via UART. I didn't see any info showed with baudrate 38400...  still trying, switch rx tx ... and going on...

even with Hercules...
<img width="670" alt="Screen Shot 2021-11-26 at 7 21 31 PM" src="https://user-images.githubusercontent.com/4170675/143573473-d74c635d-f114-4649-a31d-781e18295961.png">

**Comment by polihedron** [comment]
Then there is no temperature readings, or no reflow parameters saved at start.
Flash bluepill with v1.1 fw, on the nextion display go to advanced menu where are pid settings, you can change something, but it's not mandatory, comeback to main screen.
Check btw is the temperature reading visible on the screen.
Relfow parameters should be saved now in flash memory.
Flash again bluepill with 1.2 fw, but do not erase, just flash and verify.
If still issue, then only debug left.

**Comment by botio** [comment]
wait.... so u fixed it???

**Comment by polihedron** [comment]
Yes, you pointed issue, I missed in code first run function which is saving configuration parameters. When someone check old firmware version v1.1 and saved parameters to flash memory, then checked my mod flashing stm32bluepill without full memory erase - my mod was working (somehow).
So when flash memory was erased, without these configuration parameters at start stm32bluepill was unable to calculate and then send reflow curve to nextion display.
I belive that was your case, but if issue still persist, then you have hardware problem to solve, use UART to USB converter to confirm that both modules: stm32bluepill and nextion display are receiving and sending data.

I'm just a beginner, my code is messy needs some general refactoring, but works.. in some circumstances ;)
Feel free to modify code and fix issues if you find any.

**Comment by polihedron** [comment]
@botio did you manage make this project working?

**Comment by daestx** [comment]
So, I used a bluepill board and it worked out of the box.
I compiled the code with STM32CubeIDE and flashed it with a segger j-link EDU
