### ISSUE TITLE
Cold junction compensation?

### ISSUE THREAD

**Issue by PricelessToolkit** [polihedron/DIY-Reflow-Oven#7]
Hi @polihedron, 
I want to do the same project and I have two questions if it's not difficult help me figure it out.

1. maybe you checked the whole area in the oven is heated evenly? I bought T-962A+ it does not warm up evenly, Cannot be used without full modification.
2. In the future do you have plans to implement cold junction compensation with a  1-wire temp sensor like DS18B20? 
3. Thanks

**Comment by polihedron** [comment]
Hi there, to be honest I didn't bother is whole area in the oven heated evenly, because there is still quite wide temperature offset for each reflow stage in solder paste datasheet. I checked two large pcbs (171mmx131) for power leds and I'm happy with results:

![IMG_20220424_131954](https://user-images.githubusercontent.com/46649005/164973965-15ae65c3-a9a6-42c9-b876-f4e59d0c8315.jpg)



Regarding to implement cold junction compensation, have you checked MAX6675 datasheet? 

![max6675](https://user-images.githubusercontent.com/46649005/164972809-bf678f17-cbfb-4431-b35c-6550e3edcba8.png)

Kind Regards

**Comment by polihedron** [comment]
@PricelessToolkit do you have any other questions regarding cold-junction compensation issue?

**Comment by PricelessToolkit** [comment]
@polihedron No, Thank you very much for responding.

**Comment by polihedron** [comment]
@PricelessToolkit ok,
good luck with project and T-962A+ mod.
