### ISSUE TITLE
Limit Max Temp 240°C

### ISSUE THREAD

**Issue by PricelessToolkit** [polihedron/DIY-Reflow-Oven#8]
Hi, I can't increase the temperature above 240°C, Is there a hardcoded limit in the code, or its a bug?

In my case thermocouple measuring air temperature (with this approach there is no PCB temperature overshoot )the difference between air temperature and PCB is 5-6°C and therefore wanted to raise the temperature ~10°C.

PS: my 8Liter and 800W

![IMG_20220513_181112](https://user-images.githubusercontent.com/81021972/169696621-70a47b9f-b38a-4f83-b4ea-9170cdb8c9f8.jpg)
![IMG_20220519_202002](https://user-images.githubusercontent.com/81021972/169696629-19e517ad-27df-4748-af46-8222b0d9f8ee.jpg)

**Comment by polihedron** [comment]
@PricelessToolkit 
Yes, there are input limits, 
look inside the HandleGui() in main.c if you want to modify them as desired.
btw. nice front panel printout.

Forgot to mention, for 250°C you will need to modify HMI file, and probably change code in main.c for chart drawing because of the new limits.
I guess STM32bluepill will draw chart line above 245, but it will be outside the white area.

**Comment by PricelessToolkit** [comment]
Thanks i faund it  
"if (Output > 240) Output = 240;"

I think 245°C is enught for me. Can you explain me how to compile this Project.  Thank you very match!!

**Comment by polihedron** [comment]
@PricelessToolkit, there are many ways to compile project, look for tutorials on internet. 
Easiest way is to open project in STM32CubeIDE and use 'compile' button..
good luck!

**Comment by PricelessToolkit** [comment]
If I succeed, I'll post the result. Thanks!!

**Comment by PricelessToolkit** [comment]
all works great,  also changed the HMI file.
![0](https://user-images.githubusercontent.com/81021972/169888517-3ca62011-ca3b-46a4-b465-7617ee468cad.png)
thanks for your help
